added alternative s3_website config for staging branch and bucket

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -3,7 +3,11 @@ set -3 #halt script on error
 
 bundle exec jekyll build
 
-# bundle exec htmlproof ./_site 
-s3_website push
-
-
+if [[ $TRAVIS_BRANCH == 'master']] ; then
+  s3_website push --config_dir staging
+elif [[ $TRAVIS_BRANCH == 'live']] ; then
+  s3_website push --cofig_dir production
+else
+  echo 'Invalid branch. you can only publish from master or live.'
+  exit 1
+fi
